export const deviceIds: string[] =
  [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10"
  ]
  export const sensorMapping:any=
  {
    deviceIdKey:"ID",
    itemsObjKey:"reportData",
    items:[
      {sensorName:"Voltage_1",
        dbKey:"Voltage",
        valueType:"number",
        unit:"V",
        type:"voltage"
      },
      {sensorName:"Current_1",
        dbKey:"I_in",
        valueType:"number",
        unit:"A",
        type:"current"
      },
      {sensorName:"Current_2",
        dbKey:"I_out",
        valueType:"number",
        unit:"A",
        type:"current"
      },
    ]
  }